// Shared Blog and Resources Data (English & Arabic)

export const CATEGORIES = [
    { id: 'all', nameEn: 'All', nameAr: 'الكل' },
    { id: 'product', nameEn: 'Product', nameAr: 'المنتج' },
    { id: 'guides', nameEn: 'Guides', nameAr: 'أدلة وإرشادات' },
    { id: 'enterprise', nameEn: 'Enterprise AI', nameAr: 'ذكاء المؤسسات' },
    { id: 'case-studies', nameEn: 'Case Studies', nameAr: 'قصص نجاح' },
    { id: 'security', nameEn: 'Security', nameAr: 'الأمان والامتثال' },
];

export const FEATURED_POST = {
    categoryEn: 'Enterprise AI',
    categoryAr: 'ذكاء المؤسسات',
    titleEn: 'How ZeroQueries Connects Structured Warehouses and Unstructured Documents in Real Time',
    titleAr: 'كيف يربط ZeroQueries بين مستودعات البيانات المهيكلة والمستندات غير المهيكلة في الوقت الفعلي',
    excerptEn: 'Learn how modern enterprise decision intelligence eliminates fragile SQL ETL pipelines and delivers instant answers directly inside Slack, WhatsApp, and executive workspaces.',
    excerptAr: 'تعرف على كيفية مساهمة ذكاء اتخاذ القرارات الحديث في إلغاء مسارات ETL المعقدة وتوفير إجابات فورية موثوقة مباشرة داخل سلاك وواتساب.',
    dateEn: 'June 29, 2026',
    dateAr: '29 يونيو 2026',
    readTimeEn: '8 min read',
    readTimeAr: 'قراءة 8 دقائق',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1000'
};

export const POSTS = [
    {
        id: 1,
        category: 'product',
        categoryEn: 'Product',
        categoryAr: 'المنتج',
        titleEn: 'Introducing Slack & WhatsApp Conversational Analytics for Teams',
        titleAr: 'إطلاق تحليلات المحادثة عبر سلاك وواتساب لفرق العمل',
        excerptEn: 'Empower frontline operators and department heads to query live warehouse data using natural language messages.',
        excerptAr: 'تمكين المشرفين ورؤساء الأقسام من استعلام بيانات المستودع الحية عبر رسائل المحادثة الطبيعية.',
        dateEn: 'May 21, 2026',
        dateAr: '21 مايو 2026',
        readTimeEn: '6 min read',
        readTimeAr: 'قراءة 6 دقائق',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 2,
        category: 'enterprise',
        categoryEn: 'Enterprise AI',
        categoryAr: 'ذكاء المؤسسات',
        titleEn: 'Deterministic SQL Grounding: Eliminating Hallucinations in Analytics',
        titleAr: 'التثبيت الحتمي لاستعلامات SQL: القضاء على الهلوسة في التحليلات',
        excerptEn: 'Why standard LLMs fail on corporate numbers and how schema-grounded deterministic validators guarantee 100% precision.',
        excerptAr: 'لماذا تخطئ النماذج اللغوية في أرقام الشركات وكيف تضمن أدوات التحقق الحتمية دقة 100٪ في النتائج.',
        dateEn: 'April 14, 2026',
        dateAr: '14 أبريل 2026',
        readTimeEn: '5 min read',
        readTimeAr: 'قراءة 5 دقائق',
        image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 3,
        category: 'product',
        categoryEn: 'Product',
        categoryAr: 'المنتج',
        titleEn: 'Direct In-Warehouse Compute: Zero Data Duplication Explained',
        titleAr: 'المعالجة المباشرة داخل المستودع: شرح مبدأ عدم نسخ البيانات',
        excerptEn: 'Keep all sensitive records within your Snowflake, BigQuery, and Databricks perimeters with ephemeral RAM processing.',
        excerptAr: 'احتفظ بجميع السجلات الحساسة داخل بيئة Snowflake وBigQuery وDatabricks الخاصة بك مع المعالجة المؤقتة في الذاكرة.',
        dateEn: 'March 25, 2026',
        dateAr: '25 مارس 2026',
        readTimeEn: '5 min read',
        readTimeAr: 'قراءة 5 دقائق',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 4,
        category: 'case-studies',
        categoryEn: 'Case Studies',
        categoryAr: 'قصص نجاح',
        titleEn: 'How Northwind Logistics Reduced Ad-hoc SQL Backlogs by 80%',
        titleAr: 'كيف خفضت Northwind للخدمات اللوجستية تراكم استعلامات SQL بنسبة 80٪',
        excerptEn: 'Discover how self-service conversational querying unlocked faster supply chain inventory decisions without wait times.',
        excerptAr: 'اكتشف كيف ساهم الاستعلام الذاتي في تسريع قرارات مخزون سلاسل الإمداد دون الحاجة لانتظار فريق البيانات.',
        dateEn: 'February 12, 2026',
        dateAr: '12 فبراير 2026',
        readTimeEn: '7 min read',
        readTimeAr: 'قراءة 7 دقائق',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 5,
        category: 'security',
        categoryEn: 'Security',
        categoryAr: 'الأمان والامتثال',
        titleEn: 'SOC 2 Type II and HIPAA: Securing Natural Language Business Intelligence',
        titleAr: 'شهادة SOC 2 وHIPAA: تأمين ذكاء الأعمال المعتمد على اللغة الطبيعية',
        excerptEn: 'A deep dive into zero-retention commercial agreements, customer-managed encryption keys, and private VPC architectures.',
        excerptAr: 'نظرة متعمقة على اتفاقيات عدم الاحتفاظ بالبيانات ومفاتيح التشفير المدارة من العميل وخيارات النشر المعزول.',
        dateEn: 'January 18, 2026',
        dateAr: '18 يناير 2026',
        readTimeEn: '9 min read',
        readTimeAr: 'قراءة 9 دقائق',
        image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 6,
        category: 'guides',
        categoryEn: 'Guides',
        categoryAr: 'أدلة وإرشادات',
        titleEn: 'Modern BI vs. Conversational AI: An Objective Architectural Comparison',
        titleAr: 'لوحات التحكم التقليدية مقابل الذكاء الاصطناعي الحواري: مقارنة موضوعية',
        excerptEn: 'Why static dashboards cause reporting bottlenecks and how conversational decision intelligence fundamentally changes data access.',
        excerptAr: 'لماذا تتسبب لوحات التحكم الثابتة في تباطؤ الأعمال وكيف يغير ذكاء القرار الحواري تجربة الوصول للبيانات.',
        dateEn: 'December 08, 2025',
        dateAr: '8 ديسمبر 2025',
        readTimeEn: '10 min read',
        readTimeAr: 'قراءة 10 دقائق',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 7,
        category: 'guides',
        categoryEn: 'Guides',
        categoryAr: 'أدلة وإرشادات',
        titleEn: 'Step-by-Step Guide: Connecting WhatsApp to Your Snowflake Warehouse',
        titleAr: 'دليل خطوة بخطوة: ربط واتساب بمستودع بيانات Snowflake',
        excerptEn: 'Configure secure webhook authentication, verify schema permissions, and start querying data on mobile in under 15 minutes.',
        excerptAr: 'إعداد مصادقة آمنة عبر الويب، والتحقق من صلاحيات المخطط، وبدء استعلام البيانات على الهاتف خلال 15 دقيقة.',
        dateEn: 'November 20, 2025',
        dateAr: '20 نوفمبر 2025',
        readTimeEn: '7 min read',
        readTimeAr: 'قراءة 7 دقائق',
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 8,
        category: 'case-studies',
        categoryEn: 'Case Studies',
        categoryAr: 'قصص نجاح',
        titleEn: 'FinTech Growth: Scaling Instant Decision Making Across 5 Regional Teams',
        titleAr: 'نمو التقنية المالية: تسريع اتخاذ القرارات الفورية عبر 5 فرق إقليمية',
        excerptEn: 'How a high-growth fintech reduced latency on executive portfolio analysis from 48 hours to zero with direct conversational queries.',
        excerptAr: 'كيف نجحت شركة تقنية مالية سريعة النمو في تقليص زمن تحليل المحافظ التنفيذية من 48 ساعة إلى ثوانٍ معدودة.',
        dateEn: 'October 15, 2025',
        dateAr: '15 أكتوبر 2025',
        readTimeEn: '6 min read',
        readTimeAr: 'قراءة 6 دقائق',
        image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=600'
    },
    {
        id: 9,
        category: 'enterprise',
        categoryEn: 'Enterprise AI',
        categoryAr: 'ذكاء المؤسسات',
        titleEn: 'Role-Based Access Control in Natural Language Querying',
        titleAr: 'التحكم في الوصول المستند إلى الأدوار في الاستعلام باللغة الطبيعية',
        excerptEn: 'Deep-dive into row-level security and permission inheritance when multiple users query the same database through team chat.',
        excerptAr: 'نظرة متعمقة على أمان مستوى الصفوف وتوريث الأذونات عندما يطرح عدة مستخدمين استفساراتهم في المحادثات الجماعية.',
        dateEn: 'September 28, 2025',
        dateAr: '28 سبتمبر 2025',
        readTimeEn: '8 min read',
        readTimeAr: 'قراءة 8 دقائق',
        image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=600'
    }
];
