import LegalPage from "@/Components/LegalPage";

export const metadata = {
  title: "Privacy Policy | ZeroQueries",
  description:
    "How ZeroQueries collects, uses, and protects your personal and business data.",
};

const SECTIONS = [
  { id: "introduction", title: "1. Introduction" },
  { id: "information-we-collect", title: "2. Information We Collect" },
  { id: "how-we-use-information", title: "3. How We Use Information" },
  { id: "zero-training-policy", title: "4. Zero-Training Policy" },
  { id: "information-sharing", title: "5. Information Sharing" },
  { id: "data-retention", title: "6. Data Retention" },
  { id: "security", title: "7. Security" },
  { id: "your-rights", title: "8. Your Rights" },
  { id: "international-transfers", title: "9. International Transfers" },
  { id: "childrens-privacy", title: "10. Children's Privacy" },
  { id: "changes", title: "11. Changes to This Policy" },
  { id: "contact", title: "12. Contact Us" },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      subtitle="How we collect, use, and protect your information when you use ZeroQueries."
      lastUpdated="October 2, 2026"
      version="3.0"
      sections={SECTIONS}
    >
      <h2 id="introduction">1. Introduction</h2>
      <p>
        This Privacy Policy describes how <strong>Invertio Software Solutions</strong>{" "}
        (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) collects, uses, and shares
        information about you when you use ZeroQueries and our related services
        (collectively, the &quot;Services&quot;).
      </p>
      <p>
        By accessing or using the Services, you agree to the collection and use
        of information in accordance with this policy. If you do not agree,
        please discontinue use of the Services.
      </p>

      <h2 id="information-we-collect">2. Information We Collect</h2>

      <h3>Information you provide to us</h3>
      <ul>
        <li>
          <strong>Account information</strong> — name, work email, organization,
          role.
        </li>
        <li>
          <strong>Billing information</strong> — processed securely by our
          third-party payment provider. We do not store full card numbers.
        </li>
        <li>
          <strong>Content you submit</strong> — questions, comments, feedback,
          and any data you choose to upload.
        </li>
        <li>
          <strong>Support communication</strong> — emails, chat transcripts,
          and call notes when you contact us.
        </li>
      </ul>

      <h3>Information collected automatically</h3>
      <ul>
        <li>
          <strong>Log data</strong> — IP address, browser type, operating
          system, referring pages, and timestamps.
        </li>
        <li>
          <strong>Usage data</strong> — features accessed, queries run, and
          interactions with the Services.
        </li>
        <li>
          <strong>Device information</strong> — hardware model, OS version, and
          unique device identifiers.
        </li>
        <li>
          <strong>Cookies and similar technologies</strong> — see our{" "}
          <a href="/cookies">Cookie Preferences</a> page for details.
        </li>
      </ul>

      <h2 id="how-we-use-information">3. How We Use Information</h2>
      <p>We use the information we collect to:</p>
      <ul>
        <li>Provide, maintain, and improve the Services.</li>
        <li>Process transactions and send related information.</li>
        <li>Respond to your comments, questions, and requests.</li>
        <li>Send administrative information such as security alerts and policy updates.</li>
        <li>Detect, prevent, and address technical or security issues.</li>
        <li>Comply with legal obligations and enforce our agreements.</li>
      </ul>

      <h2 id="zero-training-policy">4. Zero-Training Policy</h2>
      <p>
        <strong>
          ZeroQueries does not use your data to train machine-learning models.
        </strong>{" "}
        This is a fundamental design commitment, not a setting you have to
        enable. Every query runs against read-only connections to your own
        infrastructure, and results are processed in memory without persistent
        storage.
      </p>
      <p>This policy applies to:</p>
      <ul>
        <li>All customer data in your warehouses and databases.</li>
        <li>Unstructured content such as PDFs and call transcripts.</li>
        <li>Questions typed into ZeroQueries.</li>
        <li>Answers, charts, and reports generated by the platform.</li>
      </ul>

      <h2 id="information-sharing">5. Information Sharing</h2>
      <p>
        <strong>We do not sell your personal information.</strong> We may share
        information with the following categories of recipients:
      </p>
      <ul>
        <li>
          <strong>Service providers</strong> — cloud hosting, error monitoring,
          payment processing, and email delivery, all under strict data
          processing agreements.
        </li>
        <li>
          <strong>Professional advisors</strong> — lawyers, auditors, and
          accountants as needed.
        </li>
        <li>
          <strong>Authorities</strong> — when required by law, subpoena, or
          valid legal process.
        </li>
        <li>
          <strong>Successors</strong> — in the event of a merger, acquisition,
          or sale of assets.
        </li>
      </ul>

      <h2 id="data-retention">6. Data Retention</h2>
      <p>
        We retain personal information for as long as your account is active,
        or for as long as needed to provide the Services and comply with legal
        obligations. You may request deletion at any time by emailing{" "}
        <a href="mailto:privacy@zeroqueries.com">privacy@zeroqueries.com</a>.
      </p>
      <p>
        Customer data stored in your own warehouses is never copied to our
        servers and is governed entirely by your own retention policies.
      </p>

      <h2 id="security">7. Security</h2>
      <p>
        We use administrative, technical, and physical safeguards to protect
        your information:
      </p>
      <ul>
        <li>AES-256 encryption at rest.</li>
        <li>TLS 1.3 encryption in transit.</li>
        <li>Role-based access control down to table and column level.</li>
        <li>Immutable audit logs of all actions.</li>
        <li>Annual third-party penetration testing.</li>
      </ul>
      <p>
        For more detail, see our <a href="/security">Security &amp; Compliance</a> page.
      </p>

      <h2 id="your-rights">8. Your Rights</h2>
      <p>
        Depending on your jurisdiction, you may have the right to:
      </p>
      <ul>
        <li>Access the personal information we hold about you.</li>
        <li>Correct inaccurate or incomplete information.</li>
        <li>Delete your personal information.</li>
        <li>Restrict or object to certain processing.</li>
        <li>Receive a portable copy of your data.</li>
        <li>Withdraw consent at any time.</li>
      </ul>
      <p>
        To exercise any of these rights, email{" "}
        <a href="mailto:privacy@zeroqueries.com">privacy@zeroqueries.com</a>. We
        respond within 30 days.
      </p>

      <h2 id="international-transfers">9. International Transfers</h2>
      <p>
        ZeroQueries may be operated from locations in India, the United States,
        the European Union, Saudi Arabia, and the UAE. When we transfer
        personal information across borders, we rely on standard contractual
        clauses and equivalent safeguards.
      </p>

      <h2 id="childrens-privacy">10. Children&apos;s Privacy</h2>
      <p>
        The Services are not directed to individuals under the age of 16. We do
        not knowingly collect personal information from children. If you
        believe a child has provided us with personal information, contact us
        and we will delete it.
      </p>

      <h2 id="changes">11. Changes to This Policy</h2>
      <p>
        We may update this policy from time to time. When we make material
        changes, we will notify you by email or through the Services. The
        &quot;Last updated&quot; date at the top of this page will always reflect
        the most recent revision.
      </p>

      <h2 id="contact">12. Contact Us</h2>
      <p>
        Questions about this policy? Reach us at{" "}
        <a href="mailto:privacy@zeroqueries.com">privacy@zeroqueries.com</a>.
      </p>
      <p>
        Invertio Software Solutions
        <br />
        HITEC City, Madhapur
        <br />
        Hyderabad, Telangana 500081, India
      </p>
    </LegalPage>
  );
}
